workflows:
  convertpdf-playstore:
    name: ConvertPDF PlayStore
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.3.10
    scripts:
      - flutter config --no-analytics  # <-- ADD THIS to skip welcome screen
      - flutter pub get
      - flutter build appbundle --release --verbose
    artifacts:
      - build/app/outputs/bundle/release/*.aab
